#!/usr/bin/env ruby

require 'fileutils'
require 'slop'
require 'clock_window'

opts = Slop.parse do |o|
  o.banner = <<-BANNER
Clock Window - "Clock your desktop activity!"
Copyright (c) 2016 Daniel P. Clark via the MIT License
Version: #{ClockWindow::VERSION}

usage: clock_window [options]
BANNER
  o.bool "-c", "--clean", "Use all known name filters"
  o.string "-o", "--output", "File/directory output in strftime"
  o.bool "-e", "--eager", "Use strftime of time at start of script\n"

  o.on "--version", "Print the version" do
    puts ClockWindow::VERSION
    exit
  end
  o.bool "-h", "--help", "This help menu\n\n"
end

if opts[:help]
  puts opts
  exit
else
  puts opts.to_s.partition("\n\n").first
  puts "\nPress CTRL-C to exit the script."
  puts "Starting active window tracking!"
end 

dir_name, _, file_name = opts[:output].to_s.rpartition(File::SEPARATOR)
file_name = "timelog.json" if file_name.empty?

@time = Time.now if opts[:eager]
puts "Start time is #{@time || Time.now}"
filter_opts = opts.clean? ? {filter_opts: {no_notify: true}} : {}
clock_it = ClockWindow::ClockIt.new(**filter_opts)
begin
  loop do
    clock_it.tick
    sleep clock_it.sleep_length
  end
ensure
  @time ||= Time.now
  clock_it.write_report(@time, dir_name, file_name)
end
